kookmin-sw/capstone-2020-21

server/apps/api/views.py

create me query

---

server/apps/api/serializers.py
server/apps/api/urls.py

implement nested router for clothes & clothes sets

---

server/apps/api/urls.py
server/apps/api/validations.py
server/apps/api/views.py
server/config/settings/base.py
server/requirements/base.txt

add user filtering

---

server/apps/api/choices.py
server/apps/api/utils.py

choices.py와 utils.py 수정하기

---

server/apps/api/serializers.py
server/apps/api/views.py
server/config/settings/local.py

change serializer & views

---

server/apps/api/serializers.py
server/apps/api/views.py

add clothes/clothes-set validation on creation +

---

web/src/components/ClosetComponent.vue
web/src/components/MainNavigation.vue
web/src/components/ReviewComponent.vue
web/src/css/login.css
web/src/router.js
web/src/views/Review.vue

Review.vue 생성하기

---

server/apps/api/views.py

today-category 엔드포인트 구현하기

---

server/apps/api/views.py

check user when modifying/deleting model objects

---

web/src/components/ClosetComponent.vue
web/src/components/ClosetDeletedComponent.vue
web/src/components/ClosetDetailComponent.vue
web/src/components/ClosetDetailInfoComponent.vue
web/src/components/ClosetModifiedComponent.vue
web/src/components/MainNavigation.vue
web/src/plugins/vue-fontawesome.js
web/src/router.js
web/src/views/Closet.vue
web/src/views/ClosetDetail.vue

ClosetDetail.vue 생성하기

---

web/src/components/MainComponent.vue
web/src/components/ReviewComponent.vue
web/src/components/TextRecommend.vue
web/src/router.js
web/src/views/Main.vue

Main.vue 생성하기

---

server/apps/api/factories.py
server/apps/api/populate.py
server/requirements/base.txt

create user factory

---

web/src/components/ClosetAddComponent.vue
web/src/components/ClosetDetailInfoComponent.vue
web/src/router.js
web/src/views/Closet.vue
web/src/views/ClosetAdd.vue
web/src/views/ClosetDetail.vue

ClosetAdd.vue 생성하기

---

web/src/components/ClassificationComponent.vue
web/src/components/CodyComponent.vue
web/src/router.js
web/src/views/Closet.vue
web/src/views/Cody.vue
web/src/views/Main.vue

Cody.vue 생성하기

---

server/apps/api/managers.py
server/apps/api/permissions.py
server/apps/api/tests.py
server/apps/api/tests/test_user.py
server/apps/api/views.py
server/requirements/test.txt

implement user tests

---

web/src/components/HomeNavigation.vue
web/src/components/LoginComponent.vue
web/src/components/ReviewComponent.vue
web/src/components/SignupComponent.vue
web/src/components/TextRecommend.vue
web/src/views/Review.vue

페이지별 다른 css 수정하기

---

server/apps/api/views.py

today_category 앤드포인트 수정하기

---

web/src/components/CodyDetailComponent.vue
web/src/router.js
web/src/views/CodyAdd.vue
web/src/views/CodyDetail.vue

resolves #78
- CodyDetailComponent.vue 추가 생성

CodyDetail.vue 생성하기

---

server/apps/api/populate.py

populate.py 수정하기

---

server/apps/api/populate.py

populate.py 예외처리 수정하기

---

web/src/components/ClassificationComponent.vue
web/src/components/ClosetModifiedComponent.vue
web/src/components/CodyComponent.vue
web/src/components/CodyDetailInfoComponent.vue
web/src/main.js
web/src/views/Closet.vue
web/src/views/ClosetAdd.vue
web/src/views/ClosetDetail.vue
web/src/views/Cody.vue
web/src/views/CodyAdd.vue
web/src/views/CodyDetail.vue

resolves #90 
-ClosetModifiedComponet 대신 v-for를 이용하여 List Rendering 함

ClosetModifiedComponent 수정하기

---

web/src/components/ImageAnalysisComponent.vue
web/src/components/ImageUploadComponent.vue
web/src/router.js
web/src/views/Closet.vue
web/src/views/ClosetAddNew.vue

add new closet add component

---

server/apps/api/tests/test_clothes.py
server/apps/api/utils.py
server/apps/api/views.py
server/config/settings/base.py

modify image processing

---

server/apps/api/views.py

modify review view

---

server/apps/api/views.py

ClothesSetReviewView 수정하기

---

server/apps/api/populate.py
server/apps/api/tests/test_clothes.py
server/apps/api/tests/test_clothes_set.py
server/apps/api/tests/test_clothes_set_review.py
server/apps/api/tests/test_user.py
server/apps/api/views.py

resolves #115 
+ error handling when weather data doesn't exist has to be added on `views.py`

update review test code

---

web/src/components/cards/ClothesCard.vue
web/src/components/cards/ClothesSetCard.vue

resolves #116 
+ review card is not done yet

basic card components

---

server/apps/api/serializers.py
web/src/components/ReviewIndexComponent.vue
web/src/components/ReviewListComponent.vue
web/src/components/cards/ClothesSetReviewCard.vue

resolves #121 
- little fix on backend: clothes set review serializer now returns string location(not location code)

create review card

---

server/apps/api/tests/test_clothes_set.py
server/apps/api/utils.py
server/apps/api/views.py
web/package-lock.json
web/package.json
web/src/components/cards/ClothesCard.vue
web/src/views/CodyAdd.vue

recreate cody add component

---

server/apps/api/views.py

add review filtering on clothes set view

---

server/scripts/save_weather.py

save_weather.py 예외처리 구현하기

---

server/apps/api/globalweather.py
server/apps/api/views.py
web/src/components/WeatherComponent.vue

add global weather feat

---

server/scripts/save_weather.py

save_weather.py에 데이터 삭제 기능 구현하기

---

web/src/views/CodyAdd.vue

handle cody add page exception

---

web/src/components/RecommendedCategoriesComponent.vue
web/src/components/WeatherComponent.vue
web/src/views/Main.vue

handle main page exception

---

server/apps/api/utils.py

resize(downscale) image before processing

---

server/apps/api/views.py

views.py 코디 리뷰 작성 시 날씨 데이터 없을 때 예외처리 구현하기

---

web/src/consts.js
web/src/views/Closet.vue

Closet.vue 예외처리하기

---

web/src/views/ClosetDetail.vue

ClosetDetail.vue 예외처리하기

---

web/src/components/ReviewComponent.vue
web/src/router.js
web/src/views/Review.vue

ReviewComponent 수정하기

---

web/src/consts.js
web/src/views/ClosetDetail.vue
web/src/views/Cody.vue

Cody.vue 예외처리하기

---

web/src/views/Cody.vue
web/src/views/CodyDetail.vue

CodyDetail.vue 예외처리하기

---

web/src/components/LoginComponent.vue
web/src/components/ReviewComponent.vue

LoginComponent 수정하기

---

server/apps/api/views.py

views.py 코디리뷰등록 예외처리 수정하기

---

web/src/components/SignupComponent.vue

SignupComponent 수정하기

---

server/apps/api/models.py
server/apps/api/views.py

resolves #175 
+ fix clothes on delete behavior(deletes corresponding cody)

edit today category

---

web/src/views/Main.vue

add lookbook component
